/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js and is used
// for TypeScript type discovery.  You do not need to edit this file.
